//
// Created by AbhishekJalkhare on 22-04-2026.
//
#include <iostream>
#include <bits/stdc++.h>
using namespace std;

int main() {
    int* ptr = nullptr;
    *ptr = 42; // Null pointer dereference triggers crash
    return 0;
}

/*
 *abhishekjalkhare@EPINHYDW180A:~/CPP_DEV_LINUX/Module11$ gdb ./Task7 core
GNU gdb (Ubuntu 15.1-1ubuntu1~24.04.1) 15.1
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Task7...
[New LWP 5910]
Downloading separate debug info for /lib/x86_64-linux-gnu/libstdc++.so.6
Downloading separate debug info for /lib/x86_64-linux-gnu/libgcc_s.so.1
--Type <RET> for more, q to quit, c to continue without paging--c
Downloading separate debug info for system-supplied DSO at 0x7fffaf5e6000
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./Task7'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00005987e782013d in main () at Task7.cpp:11

warning: Source file is more recent than executable.
11          *ptr = 42; // Null pointer dereference triggers crash
(gdb) bt
#0  0x00005987e782013d in main () at Task7.cpp:11
(gdb) l
6       #include <bits/stdc++.h>
7       using namespace std;
8
9       int main() {
10          int* ptr = nullptr;
11          *ptr = 42; // Null pointer dereference triggers crash
12          return 0;
13      }
14
15
(gdb) frame 0
#0  0x00005987e782013d in main () at Task7.cpp:11
11          *ptr = 42; // Null pointer dereference triggers crash
(gdb) info locals
ptr = 0x0
(gdb) print ptr
$1 = (int *) 0x0
(gdb) fram 0
#0  0x00005987e782013d in main () at Task7.cpp:11
11          *ptr = 42; // Null pointer dereference triggers crash
(gdb) info args
No arguments.

 */